# Generated by Django 5.2.1 on 2025-05-25 17:42

from random import choices
from django.db import migrations
from django.core.management import call_command
from django.utils.lorem_ipsum import sentence, words

from fts.web.models import Item


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial', app_label='web')


def gen_items(apps, schema_editor):
    items = [
        Item(
            name=words(2, False),
            part_no=''.join(choices('0123456789ABCDEF', k=8)),
            desc=sentence()
        ) for _ in range(500)
    ]
    Item.objects.bulk_create(items)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
        migrations.RunPython(gen_items),
    ]
